linkWorkspacePackages: true
packages:
  - configs/*
  - packages/*
  - platforms/*

overrides:
  # Fix critical vulnerabilities
  'fast-xml-parser': '>=4.5.4'
  'shell-quote': '>=1.8.4'

minimumReleaseAge: 10080 # 7 days
