ignores: [
  '@codeceptjs/allure-legacy',

  # These are dependencies for vite and vite plugins that depcheck doesn't recognize as being used
  '@vitest/coverage-v8',

  # These are vite aliases / tsconfig paths that point to specific local directories
  # Note the \ is necessary to escape the # or the ignore doesn't work
  '\#src',
  '\#test',
  '\#types',
  '\#components',
  '\#utils',
  'src', # This is used in src/styles, which recognizes absolute paths from the repo root
  'allure-commandline', # To support e2e-reports
  'i18next-parser', # For extracting i18next translation keys
  'npm-run-all', # To run linting checks
  'virtual:pwa-register', # Service Worker code is injected at build time
  'vite-plugin-pwa/client', # Used to generate pwa framework
  'reflect-metadata', # Used for ioc resolution
  '@babel/plugin-proposal-decorators', # Used to build with decorators for ioc resolution
  'babel-plugin-transform-typescript-metadata', # Used to build with decorators for ioc resolution
  '@babel/core', # Required peer dependency for babel plugins above

  'eslint-plugin-react', # Installed by eslint config
  'eslint-plugin-react-hooks', # Installed by eslint config
]
