name: Release - Build Artifacts, Tag, and Release

on:
  workflow_dispatch:
  push:
    branches: ['release']

jobs:
  create-new-release-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # ghapm:v4
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # ghapm:v4
        with:
          node-version: 24
      - name: Install pnpm
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # ghapm:v3
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Get current package version
        id: package-version
        run: |
          version=$( jq -r .version package.json)
          echo "current-version=${version}" >> "$GITHUB_OUTPUT"

      - name: Build App
        working-directory: ./platforms/web
        run: |
          pnpm build
          cd build
          tar czf ott-web-app-build-${{steps.package-version.outputs.current-version}}.tar.gz public
          zip -r ott-web-app-build-${{steps.package-version.outputs.current-version}}.zip public

      - name: Parse Changelog Entry
        id: changelog-reader
        uses: coditory/changelog-parser@4f567c6914ee75eff434b4d946393dfd254f8f98 # ghapm:v1
        with:
          version: ${{ steps.package-version.outputs.current-version }}

      - name: Append Release Notes
        run: |
          cat <<EOT >> .github/RELEASE_BODY_TEMPLATE.md
          ${{ steps.changelog-reader.outputs.description }}
          EOT
          echo "Appended release notes"

      - name: Create Tag
        run: git tag ${{ steps.package-version.outputs.current-version }}

      - name: Release
        uses: ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5 # ghapm:v1
        if: ${{ steps.package-version.outputs.current-version }}
        with:
          commit: 'release'
          artifacts: 'platforms/web/build/ott-web-app-build-*.tar.gz, platforms/web/build/ott-web-app-build-*.zip'
          tag: v${{ steps.package-version.outputs.current-version }}
          bodyFile: '.github/RELEASE_BODY_TEMPLATE.md'
          token: ${{ secrets.GITHUB_TOKEN }}
