name: Web - Test - PR Deploy Preview and Lighthouse Test

on:
  pull_request:

defaults:
  run:
    working-directory: ./platforms/web

jobs:
  build_and_preview:
    name: Build and preview
    if: '! github.event.pull_request.head.repo.fork '
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.firebase_hosting_preview.outputs.details_url }}
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # ghapm:v3
      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # ghapm:v4
        with:
          node-version: "24.18.0" # https://github.com/FirebaseExtended/action-hosting-deploy/issues/460#issuecomment-4832552057
      - name: Install pnpm
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # ghapm:v3
      - name: Build Preview Link
        env:
          APP_PLAYER_LICENSE_KEY: ${{ secrets.PLAYER_LICENSE_KEY }}
        run: pnpm install && MODE=preview pnpm build
      - uses: FirebaseExtended/action-hosting-deploy@500ac625ca2dd40cbd15f7659af953801858032a # ghapm:v0
        id: firebase_hosting_preview
        with:
          entryPoint: './platforms/web'
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          expires: 30d

  lhci:
    name: Lighthouse
    if: '! github.event.pull_request.head.repo.fork '
    runs-on: ubuntu-latest
    needs: build_and_preview
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # ghapm:v3
      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # ghapm:v4
        with:
          node-version: "24.18.0" # https://github.com/FirebaseExtended/action-hosting-deploy/issues/460#issuecomment-4832552057
      - name: Install pnpm
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # ghapm:v3
      - name: Install Lighthouse CI
        run: pnpm add -D @lhci/cli@0.12.x
      - name: Run Lighthouse CI
        run: pnpm exec lhci autorun --collect.url=${{ needs.build_and_preview.outputs.output1 }}?app-config=gnnuzabk --config=./lighthouserc.cjs
